import re                                       #module to work in regular expression
phoneNumberFile = open('PhoneNumbers.Txt','r')  #opens txt file
phoneNumberData = phoneNumberFile.read()        #reads txt file
phoneNumberList = phoneNumberData.split("\n")   #makes a list of where each row is an item

for index,x in list(enumerate(phoneNumberList)):     #loop to go through all items in list
    x = re.sub('[^0-9]','', x)    #removes non-numeric values
    x = "(" + x[:3] + ")" + x[3:] #adds brackets
    x = x[:5] + " " + x[5:]       #adds space
    x = x[:-4] + "-" + x[-4:]     #adds hyphen
    phoneNumberList[index] = x    #rewrites list item

#formatted_numbers = ["(" + number[:3] + ")" + number[3:] for number in phoneNumberList]

#spaced_numbers = [number[:5] + " " + number[5:] for number in formatted_numbers]          This is code generated by ai

#hyphen_numbers = [number[:-4] + "-" + number[-4:] for number in spaced_numbers]

print(phoneNumberList)





